// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhhwoSE3ZziQybbgQKAa602OTHxIY0K3U',
    appId: '1:176753539277:android:cdd65105d41a6db9935184',
    messagingSenderId: '176753539277',
    projectId: 'egapp-baf50',
    storageBucket: 'egapp-baf50.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhhwoSE3ZziQybbgQKAa602OTHxIY0K3U', // Reusing Android API key for local web testing
    appId: '1:176753539277:web:cdd65105d41a6db9935184', // Placeholder Web App ID
    messagingSenderId: '176753539277',
    projectId: 'egapp-baf50',
    storageBucket: 'egapp-baf50.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtrPzvH_h5hMvviYPRpk78y1qcDxX2rhI',
    appId: '1:176753539277:ios:d05d435fa5fd9370935184',
    messagingSenderId: '176753539277',
    projectId: 'egapp-baf50',
    storageBucket: 'egapp-baf50.firebasestorage.app',
    iosBundleId: 'com.egapp.egappMovil',
  );
}
